version: "3.9"
services:
  api_gateway:
    container_name: api_gateway
    build:
      context: ./ivi-clone-api-gateway
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "3111:3111"
    restart: always

  auth:
    container_name: auth
    build:
      context: ./ivi-clone-auth-ms
      dockerfile: ./Dockerfile
      target: development
    environment:
      - RMQ_URL=amqp://rabbitmq:5672
      - DB_HOST=auth_pg
    restart: always
    depends_on:
      - auth_pg

  auth_pg:
    container_name: auth_pg
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432"
    restart: always

  comments:
    container_name: comments
    build:
      context: ./ivi-clone-comments-ms
      dockerfile: ./Dockerfile
      target: development
    environment:
      - RMQ_URL=amqp://rabbitmq:5672
      - DB_HOST=comments_pg
    restart: always
    depends_on:
      - comments_pg

  comments_pg:
    container_name: comments_pg
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432"
    restart: always

  genres:
    container_name: genres
    build:
      context: ./ivi-clone-genres-ms
      dockerfile: ./Dockerfile
      target: development
    environment:
      - RMQ_URL=amqp://rabbitmq:5672
      - DB_HOST=genres_pg
    restart: always
    ports:
      - "3200:3200"
    depends_on:
      - genres_pg

  genres_pg:
    container_name: genres_pg
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: genres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432"
    restart: always

  movies:
    container_name: movies
    build:
      context: ./ivi-clone-movies-ms
      dockerfile: ./Dockerfile
      target: development
    environment:
      - RMQ_URL=amqp://rabbitmq:5672
      - DB_HOST=movies_pg
    restart: always
    depends_on:
      - movies_pg

  movies_pg:
    container_name: movies_pg
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432"
    restart: always

  persons:
    container_name: persons
    build:
      context: ./ivi-clone-persons-ms
      dockerfile: ./Dockerfile
      target: development
    environment:
      - RMQ_URL=amqp://rabbitmq:5672
      - DB_HOST=persons_pg
    restart: always
    depends_on:
      - persons_pg

  persons_pg:
    container_name: persons_pg
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: persons
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432"
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.3-management
    restart: always
    ports:
      - "5672"